pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "BUILDING"
      }
    }

    stage('SonarCloud') {
      steps {
        echo "SONARCLOUD  STSTIC CODE ANALYSIS"
        sonar-scanner
      }
    }

    stage('Testing') {
      steps {
        warnError(message: 'Failed to Run') {
          sh '''cd cidr_convert_api/go/

golint api.go convert.go convert_test.go

go test'''
        }

        sh 'echo "UNIT TESTING"'
      }
    }

    stage('Deploy') {
      steps {
        sh '''echo "Test"

'''
      }
    }

  }
  environment {
    build = 'false'
  }
}
