pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'BUILDING'
      }
    }

    stage('SonarCloud') {
      steps {
        echo 'SONARCLOUD STATIC CODE ANALYSIS'
      }
    }

    stage('Testing') {
      steps {
        warnError(message: 'Failed to Run') {
          sh 'go version'
        }

      }
    }

    stage('Deploy') {
      steps {
        echo 'Test'
      }
    }

  }
  tools {
    go 'go-1.15'
  }
  environment {
    GO111MODULE = 'on'
  }
}